# Generated by Django 4.1.6 on 2023-02-11 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Brand_Image',
        ),
    ]
