# Generated by Django 4.1.6 on 2023-02-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_image_brand_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand_Image',
            new_name='Brands',
        ),
    ]
