# Generated by Django 4.1.6 on 2023-02-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='details',
            field=models.CharField(default='backed up with AI power and machine Learning', max_length=60),
        ),
        migrations.AlterField(
            model_name='service',
            name='text',
            field=models.CharField(max_length=40),
        ),
    ]
