# Generated by Django 4.1.6 on 2023-02-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_service_details_alter_service_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimoney', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='testimonials vid and img')),
            ],
        ),
    ]
