# Generated by Django 4.1.6 on 2023-02-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='campany_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='position_of_client',
            field=models.TextField(default='Worker'),
        ),
    ]
