# Generated by Django 4.1.6 on 2023-02-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_testimonials_campany_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='campany_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='position_of_client',
            field=models.CharField(default='Worker', max_length=200),
        ),
    ]
