# Generated by Django 4.1.6 on 2023-02-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_testimonials_campany_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other_Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimoney', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('position_of_client', models.CharField(default='worker', max_length=200)),
                ('company_name', models.CharField(default='', max_length=200)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
