# Generated by Django 4.1.6 on 2023-03-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_other_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('detail', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
