# Generated by Django 4.1.6 on 2023-03-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
